# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Juan's BLOG
email: chengjuan555@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Peasonal Staff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.github.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  cj555

# Build settings
markdown: kramdown
